<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS001_Create Store and Install app</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>caf1a313-37b2-4c7f-93de-86ca503968be</testSuiteGuid>
   <testCaseLink>
      <guid>1866f843-c27c-4202-99fa-c5775437a754</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC001_Login Shopify</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b8a6fed-c4ac-44e7-975c-68ed6bc7b80b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76abd341-c34f-4ce9-9661-45818d12d302</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4fef3572-ca3f-41c9-b6b7-11e488377625</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>48a9f160-faf8-4aa6-b765-1c447e8e7b9a</id>
         <masked>false</masked>
         <name>store_name</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/TC002_Create New Store</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad809adf-52e0-4c5d-8a42-27f762276f53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5551cd64-8721-44ec-b48a-ad3dc7b6038c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>48a9f160-faf8-4aa6-b765-1c447e8e7b9a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b2120fa2-dac3-4590-8cfe-4fa0c67e5ea0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC003_Install app</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5c4bf19-6a58-4776-8ed9-1f0c3dc33f61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2419a49-698b-4487-98d3-bdc77568709b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b6580dd2-a1b3-4626-9992-e4bf4bf7a7dc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CommonTestCase/Close Browser</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
